### ISSUE TITLE
ErrorMapper -> sourceMappedStackTrace -> outStack SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by 923132714** [923132714/ScreepsScript#13]
```shell
【global】 重新挂载拓展
[下午6:01:05][shardSeason]ErrorMapper -> sourceMappedStackTrace -> outStack SyntaxError: Unexpected end of JSON input
[shardSeason]SyntaxError: Unexpected end of JSON input
    at initDelayTasks  (../src/modules/delayQueue/index.ts:78:22)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.execLifecycleCallback  (../src/modules/framework/index.ts:173:11)
    at App.onGlobalReset  (../src/modules/framework/index.ts:156:9)
    at App.run  (../src/modules/framework/index.ts:136:37)
    at Object.loop  (../src/main.ts:40:6)
```

**Comment by 923132714** [comment]
我尝试下`Memory.delayTasks=""`

**Comment by 923132714** [comment]
无法再现
