### ISSUE TITLE
 target 阶段 transfer 出现异常，错误码 -12 creep.callDefender is not a function

### ISSUE THREAD

**Issue by 923132714** [923132714/ScreepsScript#16]
```shell
【E12N27 E12N27 remoteHarvester0】 target 阶段 transfer 出现异常，错误码 -12
[下午10:13:10][shardSeason]TypeError: creep.callDefender is not a function
    at Object.source  (../src/role/remote/remoteHarvester.ts:76:12)
    at CreepExtension.onWork  (../src/mount/CreepExtension/CreepExtension.ts:84:44)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:191:35)
    at App.do  (../src/modules/framework/index.ts:191:14)
    at App.run  (../src/modules/framework/index.ts:143:12)
    at Object.loop  (../src/main.ts:44:6)
```
代码中没有 callDefender  这个方法的实现

**Comment by 923132714** [comment]
4ca8459 解决
