### ISSUE TITLE
]TypeError: Cannot use 'in' operator to search for 'level' in undefined

### ISSUE THREAD

**Issue by 923132714** [923132714/ScreepsScript#17]
大号从去年代码更新到最新的发生问题
```
[上午10:17:33][shard3]TypeError: Cannot use 'in' operator to search for 'level' in undefined
    at FactoryHelp.handleInsufficientResource  (../src/mount/StructureExtension/FactoryExtension/FactoryExtension.ts:132:13)
    at FactoryHelp.getResource  (../src/mount/StructureExtension/FactoryExtension/FactoryExtension.ts:223:21)
    at FactoryHelp.runFactory  (../src/mount/StructureExtension/FactoryExtension/FactoryExtension.ts:46:13)
    at FactoryHelp.onWork  (../src/mount/StructureExtension/FactoryExtension/FactoryExtension.ts:25:13)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
[上午10:17:36][shard3]TypeError: this.memory.find is not a function
    at RoomPowerController.hasTask  (../src/modules/room/power/controller.ts:174:25)
    at RoomPowerController.addTask  (../src/modules/room/power/controller.ts:40:16)
    at RoomSpawnController.runSpawn  (../src/modules/room/spawn/index.ts:125:26)
    at SpawnExtension.onWork  (../src/mount/StructureExtension/SpawnExtension/SpawnExtension.ts:9:22)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
```

**Comment by 923132714** [comment]
尝试清理room.memory.factory.taskList level 都无效

```
Memory.stats={};
Memory.stats.rooms={};

_.forEach(Game.creeps,(creep,creepName)=>{
    if (creep){
        creep.suicide();
        if(Memory.creeps[creepName])
            delete Memory.creeps[creepName]
}})

_.forEach(Game.rooms,(room,roomName)=>
{
    if(room.controller){
        delete room.memory.spawnList;
        room.memory.powerTasks ="";
        if(room.memory.factory)room.memory.factory.taskList=[];
    }
}
)
_.forEach(Game.rooms,(room,roomName)=>
{
    if(room.controller){
        room.controller.stateScanner();
 room.spawner.release.harvester();
        room.spawner.release.changeBaseUnit("manager",0);
        room.spawner.release.changeBaseUnit("worker",0);
        room.spawner.release.processor();
    }
}
)


```

**Comment by 923132714** [comment]
仍未解决

**Comment by 923132714** [comment]
8919e43 已解决
