### ISSUE TITLE
ypeError: Cannot read property 'lookFor' of undefined

### ISSUE THREAD

**Issue by 923132714** [923132714/ScreepsScript#21]
:01][shard2]TypeError: Cannot read property 'lookFor' of undefined
    at Function.goToInner  (../src/modules/move/Move.ts:145:9)
    at Function.goTo  (../src/modules/move/Move.ts:196:24)
    at CreepExtension.goTo  (../src/mount/CreepExtension/CreepExtension.ts:103:16)
    at Object.target  (../src/role/war/rangedAttacker.ts:29:12)
    at CreepExtension.onWork  (../src/mount/CreepExtension/CreepExtension.ts:82:44)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:191:35)
    at App.do  (../src/modules/framework/index.ts:191:14)

**Comment by 923132714** [comment]
未重现，无法定位，后续遇到在解决

**Comment by 923132714** [comment]
未重现，无法定位，后续遇到在解决
