### ISSUE TITLE
重新挂载时会报错

### ISSUE THREAD

**Issue by 923132714** [923132714/ScreepsScript#25]
```
[上午11:34:07][shard3]ErrorMapper -> sourceMappedStackTrace -> outStack TypeError: Cannot read property 'x' of undefined
[上午11:34:07][shard3]TypeError: Cannot read property 'x' of undefined
    at JSON.parse.map  (../src/modules/ConstructionController/index.ts:55:40)
    at initConstructionController  (../src/modules/ConstructionController/index.ts:52:61)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.execLifecycleCallback  (../src/modules/framework/index.ts:173:11)
    at App.onGlobalReset  (../src/modules/framework/index.ts:156:9)
    at App.run  (../src/modules/framework/index.ts:136:37)
    at Object.loop  (../src/main.ts:44:6)
```

**Comment by 923132714** [comment]
c2eb18f 已解决
