### ISSUE TITLE
 Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by 923132714** [923132714/ScreepsScript#32]
```
[下午7:29:43][shard3]TypeError: Cannot read property 'x' of undefined
    at RoomHelp.serializePos  (../src/mount/RoomExtension/RoomExtension.ts:34:19)
    at Function.findPath  (../src/modules/move/Move.ts:240:73)
    at Function.goToInner  (../src/modules/move/Move.ts:95:33)
    at Function.goTo  (../src/modules/move/Move.ts:196:24)
    at CreepExtension.goTo  (../src/mount/CreepExtension/CreepExtension.ts:104:16)
    at Object.inPlace  (../src/utils/creep/inPlaceBase.ts:13:12)
    at CreepExtension.onWork  (../src/mount/CreepExtension/CreepExtension.ts:68:65)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:191:35)

```

**Comment by 923132714** [comment]
未重现
